/* Table definitions */
CREATE TABLE Dispositivo (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY, 
    marca VARCHAR2(100) NOT NULL, 
    modelo VARCHAR2(100) NOT NULL, 
    imei  NUMBER(15) NOT NULL, 
    id_usuario NUMBER,
    PRIMARY KEY(id)
);

CREATE TABLE Artista (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY, 
    nome VARCHAR2(200) NOT NULL,
    id_usuario NUMBER,
    PRIMARY KEY(id)
);

CREATE TABLE Podcaster (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY, 
    nome  VARCHAR2(200) NOT NULL,
    id_usuario NUMBER,
    PRIMARY KEY(id)
);

CREATE TABLE Biblioteca (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY, 
    nome  VARCHAR2(200) NOT NULL,
    id_usuario NUMBER,
    PRIMARY KEY(id)
);

CREATE TABLE Album (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY, 
    nome  VARCHAR2(200) NOT NULL,
    ano_lancamento  NUMBER(4) NOT NULL,
    id_artista NUMBER,
    PRIMARY KEY(id)
);

CREATE TABLE Musica (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY, 
    faixa  NUMBER NOT NULL,
    nome  VARCHAR2(200) NOT NULL,
    duracao INTERVAL DAY TO SECOND NOT NULL,
    genero1  VARCHAR2(200) NOT NULL,
    genero2  VARCHAR2(200),
    id_album NUMBER,
    PRIMARY KEY(id)
);

CREATE TABLE Podcast (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY, 
    nome  VARCHAR2(100) NOT NULL,
    duracao  INTERVAL DAY TO SECOND NOT NULL,
    data_lancamento  DATE NOT NULL,
    tema1  VARCHAR2(100) NOT NULL,
    tema2  VARCHAR2(100),
    tema3  VARCHAR2(100),
    id_podcaster NUMBER,
    PRIMARY KEY(id)
);

CREATE TABLE Playlist (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY, 
    id_autor  NUMBER NOT NULL,
    nome  VARCHAR2(200) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE Desconto (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY, 
    porcentagem  FLOAT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE Audiobook (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR2(200) NOT NULL, 
    autor  VARCHAR2(200) NOT NULL,
    tema  VARCHAR2(200) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE Comprar (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY,
    id_usuario  NUMBER NOT NULL,
    id_audiobook  NUMBER NOT NULL,
    id_desconto  NUMBER NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE BibliotecaUsuario (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY,
    id_usuario  NUMBER NOT NULL,
    id_biblioteca  NUMBER NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE Usuario (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY,
    email  VARCHAR2(100) NOT NULL,
    nome  VARCHAR2(200) NOT NULL,
    senha  VARCHAR2(200) NOT NULL,
    forma_pagamento  VARCHAR2(200) NOT NULL,
    promocao  VARCHAR2(200) NOT NULL,
    tipo_plano  VARCHAR2(200) NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE Seguindo (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY,
    id_usuario NUMBER,
    id_seguidor NUMBER,
    PRIMARY KEY(id)
);


CREATE TABLE AdicionaPodcaster (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY,
    id_biblioteca NUMBER,
    id_podcaster NUMBER,
    PRIMARY KEY(id)
);


CREATE TABLE AdicionaArtista (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY,
    id_biblioteca NUMBER,
    id_artista NUMBER,
    PRIMARY KEY(id)
);

CREATE TABLE AdicionaAlbum (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY,
    id_biblioteca NUMBER,
    id_album NUMBER,
    PRIMARY KEY(id)
);

CREATE TABLE PlaylistPodcaster (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY,
    id_usuario NUMBER,
    id_playlist NUMBER,
    id_podcaster NUMBER,
    PRIMARY KEY(id)
);

CREATE TABLE PlaylistMusica (
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY,
    id_usuario NUMBER,
    id_playlist NUMBER,
    id_musica NUMBER,
    PRIMARY KEY(id)
);

/* Foreign Keys */
ALTER TABLE Artista ADD FOREIGN KEY (id_usuario) REFERENCES Usuario (id);
ALTER TABLE Podcaster ADD FOREIGN KEY (id_usuario) REFERENCES Usuario (id);
ALTER TABLE Dispositivo ADD FOREIGN KEY (id_usuario) REFERENCES Usuario (id);

ALTER TABLE Playlist ADD FOREIGN KEY (id_autor) REFERENCES Usuario (id);

ALTER TABLE Comprar ADD FOREIGN KEY (id_usuario) REFERENCES Usuario (id);
ALTER TABLE Comprar ADD FOREIGN KEY (id_audiobook) REFERENCES Audiobook (id);
ALTER TABLE Comprar ADD FOREIGN KEY (id_desconto) REFERENCES Desconto (id);

ALTER TABLE BibliotecaUsuario ADD FOREIGN KEY (id_usuario) REFERENCES Usuario (id);
ALTER TABLE BibliotecaUsuario ADD FOREIGN KEY (id_biblioteca) REFERENCES Biblioteca (id);

ALTER TABLE Artista ADD FOREIGN KEY (id_usuario) REFERENCES Usuario (id);

ALTER TABLE Album ADD FOREIGN KEY (id_artista) REFERENCES Artista (id);

ALTER TABLE Podcast ADD FOREIGN KEY (id_podcaster) REFERENCES Podcaster (id);

ALTER TABLE Musica ADD FOREIGN KEY (id_album) REFERENCES Album (id);

ALTER TABLE Seguindo ADD FOREIGN KEY (id_usuario) REFERENCES Usuario (id);
ALTER TABLE Seguindo ADD FOREIGN KEY (id_seguidor) REFERENCES Usuario (id);

ALTER TABLE AdicionaPodcaster ADD FOREIGN KEY (id_biblioteca) REFERENCES Biblioteca (id);
ALTER TABLE AdicionaPodcaster ADD FOREIGN KEY (id_podcaster) REFERENCES Podcaster (id);

ALTER TABLE AdicionaArtista ADD FOREIGN KEY (id_biblioteca) REFERENCES Biblioteca (id);
ALTER TABLE AdicionaArtista ADD FOREIGN KEY (id_artista) REFERENCES Artista (id);

ALTER TABLE AdicionaAlbum ADD FOREIGN KEY (id_biblioteca) REFERENCES Biblioteca (id);
ALTER TABLE AdicionaAlbum ADD FOREIGN KEY (id_album) REFERENCES Album (id);

ALTER TABLE PlaylistPodcaster ADD FOREIGN KEY (id_usuario) REFERENCES Usuario (id);
ALTER TABLE PlaylistPodcaster ADD FOREIGN KEY (id_playlist) REFERENCES Playlist (id);
ALTER TABLE PlaylistPodcaster ADD FOREIGN KEY (id_podcaster) REFERENCES Podcaster (id);

ALTER TABLE PlaylistMusica ADD FOREIGN KEY (id_usuario) REFERENCES Usuario (id);
ALTER TABLE PlaylistMusica ADD FOREIGN KEY (id_playlist) REFERENCES Playlist (id);
ALTER TABLE PlaylistMusica ADD FOREIGN KEY (id_musica) REFERENCES Musica (id);